name: scrape data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: tor-actions/setup-tor@main
        with:
          daemon: true
          port: 9150

      - name: Scrape data
        run: |
          uv run main.py

      - uses: stefanzweifel/git-auto-commit-action@v5
