name: scrape data

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Run tests
      #  run: pytest

      - name: Scrape data
        run: |
          python3 main.py

      - name: Install git
        run: sudo apt-get install git -y

      - name: Setup username
        run: sudo git config --system user.name "scraperobot"

      - name: Setup user email
        run: sudo git config --system user.email "scraperobot@robot.com"

      - name: Setup git auth
        run: git remote set-url origin https://scraperobot:${{ secrets.GITHUB_TOKEN }}@github.com/jr-b/plages-qc.git

      - name: Fetch
        run: git fetch

      - name: Checkout branch main
        run: git checkout main

      - name: Git add
        run: git add -u

      - name: Git add
        run: git add plages.json

      - name: Commit code
        id: commitcode
        run: git commit -a -m "Update data"
        continue-on-error: true

      - name: Push code
        if: steps.commitcode.outcome == 'success'
        run: git push
        continue-on-error: true
