name: scrape data

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *" # every day at 8
    - cron: "0 21 * * *" # every day at 21

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: tor-actions/setup-tor@main
        with:
          daemon: true
          port: 9150

      - name: Scrape data
        run: |
          python3 main.py
        env:
          GSHEETS: ${{ secrets.GSHEETS }}

      - uses: stefanzweifel/git-auto-commit-action@v5
